-- H2 2.2.224;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'a835e2f75031e85c' HASH 'bab4fa2c1e13092abd4ba6bc443b1cd471e42b69bf7e0e2eb585a1738ffd2cce' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."PERSON"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 84) NOT NULL,
    "ADDRESS" CHARACTER VARYING(255),
    "EMAIL" CHARACTER VARYING(255),
    "FIRST_NAME" CHARACTER VARYING(50),
    "LAST_NAME" CHARACTER VARYING(50),
    "PERSON_ROLE" CHARACTER VARYING(255),
    "PHONE_NUMBER" CHARACTER VARYING(50),
    "ARCHIVED" BOOLEAN DEFAULT FALSE,
    "PASSWORD" CHARACTER VARYING(100)
);         
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8C7" PRIMARY KEY("ID");     
-- 18 +/- SELECT COUNT(*) FROM PUBLIC.PERSON; 
INSERT INTO "PUBLIC"."PERSON" VALUES
(65, '123 Main St, Austin, TX', 'emily.clark@gmail.com', 'Emily', 'Clark', 'CUSTOMER', '+15125551234', FALSE, NULL),
(66, '501 Rio Grande St, Austin, TX', 'c.ramirez@yahoo.com', 'Carlos', 'Ramirez', 'CUSTOMER', '+15126667890', FALSE, NULL),
(67, 'Olav Kyrres gate 21, Oslo, Norway', 'ingrid.bjornsen@outlook.com', 'Ingrid', U&'Bj\00f8rnsen', 'CUSTOMER', '+4798321199', FALSE, NULL),
(68, '14 Main St, Cork, Ireland', 'liam.oreilly@gmail.com', 'Liam', 'O''Reilly', 'CUSTOMER', '+353871234567', FALSE, NULL),
(69, '22 Victoria Rd, London, UK', 'aisha.khan@hotmail.com', 'Aisha', 'Khan', 'CUSTOMER', '+447911223344', FALSE, NULL),
(70, '456 Corporate Ave, Austin, TX', 'michael.thompson@tmc.com', 'Michael', 'Thompson', 'CONSULTANT', '+15124441234', FALSE, NULL),
(71, U&'Karenslyst all\00e9 12, Oslo, Norway', 'kari.nilsen@tmc.no', 'Kari', 'Nilsen', 'CONSULTANT', '+4798547766', FALSE, NULL),
(72, '811 Tech Drive, Austin, TX', 'james.anderson@tmc.com', 'James', 'Anderson', 'CONSULTANT', '+15127778900', FALSE, NULL),
(74, 'Testveien 123, Oslo, Norway', 'john@tmc.no', 'John', 'Doe', 'CONSULTANT', '+4798765432', FALSE, 'demo123'),
(75, '890 Oak Dr, Austin, TX', 'sofia.martinez@gmail.com', 'Sofia', 'Martinez', 'CUSTOMER', '+15129993456', FALSE, NULL),
(76, U&'L\00f8kkeveien 11, Stavanger, Norway', 'erik.hansen@outlook.com', 'Erik', 'Hansen', 'CUSTOMER', '+4798123456', FALSE, NULL),
(77, 'Nydalsveien 25, Oslo, Norway', 'nora.berg@yahoo.com', 'Nora', 'Berg', 'CUSTOMER', '+4799551122', FALSE, NULL),
(78, '1401 Congress Ave, Austin, TX', 'daniel.nguyen@gmail.com', 'Daniel', 'Nguyen', 'CUSTOMER', '+15127770001', FALSE, NULL),
(79, '88 Baker St, London, UK', 'olivia.chen@hotmail.com', 'Olivia', 'Chen', 'CUSTOMER', '+447788990011', FALSE, NULL),
(80, 'Trondheimsveien 7, Oslo, Norway', 'jonas.kristoffersen@live.no', 'Jonas', 'Kristoffersen', 'CUSTOMER', '+4799112233', FALSE, NULL),
(81, '12 Rue Lafayette, Paris, France', 'chloe.dubois@gmail.com', 'Chloe', 'Dubois', 'CUSTOMER', '+33699887766', FALSE, NULL),
(82, '200 George St, Sydney, Australia', 'amelia.white@yahoo.com', 'Amelia', 'White', 'CUSTOMER', '+61299887766', FALSE, NULL),
(83, 'Al Maktoum St, NY', 'mohammed.alfars@gmail.com', 'Mohammed', 'Al-Farsi', 'CUSTOMER', '+971504445566', FALSE, NULL);               
CREATE CACHED TABLE "PUBLIC"."ORDERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 97) NOT NULL,
    "END_DATE" DATE NOT NULL,
    "FROM_ADDRESS" CHARACTER VARYING(255),
    "NOTE" CHARACTER VARYING(255),
    "SERVICE_TYPE" CHARACTER VARYING(255) NOT NULL,
    "START_DATE" DATE NOT NULL,
    "STATUS" CHARACTER VARYING(255) NOT NULL,
    "TO_ADDRESS" CHARACTER VARYING(255),
    "CONSULTANT_ID" BIGINT,
    "CUSTOMER_ID" BIGINT,
    "LAST_UPDATED" TIMESTAMP(6),
    "MODIFIED_BY_CONSULTANT_ID" BIGINT,
    "PARENT_ORDER_ID" BIGINT
);           
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B7" PRIMARY KEY("ID");     
-- 12 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS; 
INSERT INTO "PUBLIC"."ORDERS" VALUES
(85, DATE '2025-07-28', '123 Main St, Austin, TX', 'Standard moving service for Emily.', 'MOVING', DATE '2025-07-28', 'IN_PROGRESS', '789 Elm St, Austin, TX', 70, 65, TIMESTAMP '2025-07-25 21:51:26.825786', NULL, NULL),
(86, DATE '2025-07-29', '501 Rio Grande St, Austin, TX', 'Move for Carlos, includes packing.', 'MOVING', DATE '2025-07-29', 'PENDING', '900 Red River St, Austin, TX', 71, 66, NULL, NULL, NULL),
(87, DATE '2025-07-30', '30 South Mall, Cork, Ireland', 'Moving for Liam with cleaning after.', 'MOVING', DATE '2025-07-30', 'PENDING', '18 Greenpark Rd, Cork, Ireland', 72, 68, NULL, NULL, NULL),
(88, DATE '2025-08-01', '22 Victoria Rd, London, UK', 'Full service for Aisha: move, pack, clean.', 'MOVING', DATE '2025-08-01', 'PENDING', '14 Oxford St, London, UK', 74, 69, NULL, NULL, NULL),
(89, DATE '2025-07-29', '501 Rio Grande St, Austin, TX', 'Packing service for Carlos before the move.', 'PACKING', DATE '2025-07-29', 'PENDING', '900 Red River St, Austin, TX', 71, 66, NULL, NULL, 86),
(90, DATE '2025-07-30', '30 South Mall, Cork, Ireland', 'Post-move cleaning for Liam.', 'CLEANING', DATE '2025-07-30', 'PENDING', '18 Greenpark Rd, Cork, Ireland', 72, 68, NULL, NULL, 87),
(91, DATE '2025-08-01', '22 Victoria Rd, London, UK', 'Packing service for Aisha''s full move.', 'PACKING', DATE '2025-08-01', 'PENDING', '14 Oxford St, London, UK', 74, 69, NULL, NULL, 88),
(92, DATE '2025-08-01', '22 Victoria Rd, London, UK', 'Cleaning service for Aisha after the move.', 'CLEANING', DATE '2025-08-01', 'PENDING', '14 Oxford St, London, UK', 74, 69, NULL, NULL, 88),
(93, DATE '2025-08-03', 'Trondheimsveien 7, Oslo, Norway', 'Full service for Jonas: move, pack, clean.', 'MOVING', DATE '2025-08-03', 'PENDING', 'Nydalsveien 25, Oslo, Norway', 72, 80, NULL, NULL, NULL),
(94, DATE '2025-08-04', '88 Baker St, London, UK', 'Standard moving for Olivia.', 'MOVING', DATE '2025-08-04', 'PENDING', '200 Queen''s Rd, London, UK', 71, 79, NULL, NULL, NULL),
(95, DATE '2025-08-03', 'Trondheimsveien 7, Oslo, Norway', 'Packing service for Jonas before move.', 'PACKING', DATE '2025-08-03', 'PENDING', 'Nydalsveien 25, Oslo, Norway', 72, 80, NULL, NULL, 93),
(96, DATE '2025-08-03', 'Trondheimsveien 7, Oslo, Norway', 'Cleaning service for Jonas after move.', 'CLEANING', DATE '2025-08-03', 'PENDING', 'Nydalsveien 25, Oslo, Norway', 72, 80, NULL, NULL, 93);
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8C" CHECK("PERSON_ROLE" IN('CUSTOMER', 'CONSULTANT')) NOCHECK;              
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B" CHECK("STATUS" IN('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')) NOCHECK;         
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" CHECK("SERVICE_TYPE" IN('MOVING', 'PACKING', 'CLEANING')) NOCHECK;       
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKR4OOSMO7DWXS7DB80BU478OPY" FOREIGN KEY("MODIFIED_BY_CONSULTANT_ID") REFERENCES "PUBLIC"."PERSON"("ID") NOCHECK;      
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FKRMHA0IHRINJTKO3BDC0UO3EUF" FOREIGN KEY("CONSULTANT_ID") REFERENCES "PUBLIC"."PERSON"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."FK8SXML705OSL4YQPVAI24HTR3W" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."PERSON"("ID") NOCHECK;    
