# Name of the GitHub Actions workflow
name: Fly Deploy Backend

# Controls when the action will run.
# This workflow runs on pushes to the 'main' branch.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  deploy:
    name: Deploy Backend App
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so the job can access it.
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Sets up the flyctl CLI tool.
      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Step 3: Deploys the application to Fly.io.
      # It uses a secret called FLY_API_TOKEN for authentication.
      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy --remote-only